service: serverless-svelte-${self:provider.region}

frameworkVersion: '>=1.60.4 <2.0.0'

custom:
  stage: ${opt:stage, 'dev'}
  stackname: ${self:service}-${self:custom.stage}
  debug: ${opt:debug, 'true'}
  serverless-iam-roles-per-function:
    defaultInherit: true

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  endpointType: REGIONAL
  runtime: nodejs12.x
  logRetentionInDays: 14
  deploymentBucket:
    name: serverless-svelte-deploys
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  server:
    name: svelte-server-${self:custom.stage}
    description: Serves Svelte website using Fastify serverless.
    handler: lambda.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    environment:
      DEBUG: ${self:custom.debug}
      REGION: ${self:provider.region}
      NODE_ENV: production
    package:
      exclude:
        - src/**
